/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch Agricultural Insight System Colors
        primary: "#004830",
        "primary-container": "#1e6145",
        "on-primary": "#ffffff",
        "on-primary-container": "#97dab6",
        "primary-fixed": "#aef1cc",
        "primary-fixed-dim": "#92d5b1",
        "on-primary-fixed": "#002113",
        "on-primary-fixed-variant": "#065137",
        "inverse-primary": "#92d5b1",

        secondary: "#466739",
        "secondary-container": "#c7eeb3",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#4c6d3e",
        "secondary-fixed": "#c7eeb3",
        "secondary-fixed-dim": "#acd199",
        "on-secondary-fixed": "#042100",
        "on-secondary-fixed-variant": "#2f4e23",

        tertiary: "#3c3f40",
        "tertiary-container": "#545657",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#cacbcc",
        "tertiary-fixed": "#e1e3e4",
        "tertiary-fixed-dim": "#c5c7c8",
        "on-tertiary-fixed": "#191c1d",
        "on-tertiary-fixed-variant": "#454748",

        surface: "#fbf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fbf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f3",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae8e7",
        "surface-container-highest": "#e4e2e1",
        "surface-variant": "#e4e2e1",
        "surface-tint": "#286a4d",

        background: "#fbf9f8",
        "on-background": "#1b1c1c",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#404943",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f2f0f0",

        outline: "#707973",
        "outline-variant": "#bfc9c1",

        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        // Legacy/helper aliases for backwards compatibility
        brand: {
          50: '#f0fdf4',
          100: '#dcfce7',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#004830',
        },
        agriDark: '#004830',
        agriGreen: '#1e6145',
        agriLight: '#c7eeb3',
        agriBg: '#fbf9f8'
      },
      fontFamily: {
        headline: ["IBM Plex Sans", "sans-serif"],
        "headline-lg": ["IBM Plex Sans", "sans-serif"],
        "headline-md": ["IBM Plex Sans", "sans-serif"],
        "headline-sm": ["IBM Plex Sans", "sans-serif"],
        "headline-lg-mobile": ["IBM Plex Sans", "sans-serif"],
        body: ["Noto Sans", "Noto Sans Sinhala", "Noto Sans Tamil", "sans-serif"],
        "body-lg": ["Noto Sans", "Noto Sans Sinhala", "Noto Sans Tamil", "sans-serif"],
        "body-md": ["Noto Sans", "Noto Sans Sinhala", "Noto Sans Tamil", "sans-serif"],
        "body-sm": ["Noto Sans", "Noto Sans Sinhala", "Noto Sans Tamil", "sans-serif"],
        label: ["IBM Plex Sans", "sans-serif"],
        "label-md": ["IBM Plex Sans", "sans-serif"],
        "label-sm": ["IBM Plex Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        unit: "4px",
        gutter: "20px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "container-max": "1200px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      boxShadow: {
        card: "0px 4px 12px rgba(0, 72, 48, 0.05)",
        "card-hover": "0px 8px 24px rgba(0, 72, 48, 0.10)",
      }
    },
  },
  plugins: [],
}
