import '../models/crop_model.dart';
import '../models/risk_analysis_model.dart';
import '../models/farmer_model.dart';
import '../models/buyer_model.dart';
import '../models/surplus_listing_model.dart';
import '../models/notice_model.dart';

class MockDataService {
  static List<Crop> getUpcountryCrops() {
    return [
      const Crop(
        id: 'crop_leeks',
        name: 'Leeks',
        sinhalaName: 'ලීක්ස්',
        category: 'Exotic Vegetable',
        maturityDays: 90,
        expectedYieldKgPerAcre: 8000,
        currentMarketPricePerKg: 220.0,
        historicalAveragePricePerKg: 180.0,
        iconEmoji: '🥬',
      ),
      const Crop(
        id: 'crop_cabbage',
        name: 'Cabbage',
        sinhalaName: 'ගෝවා',
        category: 'Exotic Vegetable',
        maturityDays: 75,
        expectedYieldKgPerAcre: 12000,
        currentMarketPricePerKg: 140.0,
        historicalAveragePricePerKg: 130.0,
        iconEmoji: '🥗',
      ),
      const Crop(
        id: 'crop_carrot',
        name: 'Carrot',
        sinhalaName: 'කැරට්',
        category: 'Root Vegetable',
        maturityDays: 90,
        expectedYieldKgPerAcre: 7500,
        currentMarketPricePerKg: 310.0,
        historicalAveragePricePerKg: 240.0,
        iconEmoji: '🥕',
      ),
      const Crop(
        id: 'crop_beetroot',
        name: 'Beetroot',
        sinhalaName: 'බීට්රූට්',
        category: 'Root Vegetable',
        maturityDays: 70,
        expectedYieldKgPerAcre: 6500,
        currentMarketPricePerKg: 280.0,
        historicalAveragePricePerKg: 220.0,
        iconEmoji: '🟣',
      ),
      const Crop(
        id: 'crop_beans',
        name: 'Green Beans',
        sinhalaName: 'බෝංචි',
        category: 'Legume',
        maturityDays: 60,
        expectedYieldKgPerAcre: 4500,
        currentMarketPricePerKg: 340.0,
        historicalAveragePricePerKg: 260.0,
        iconEmoji: '🫘',
      ),
      const Crop(
        id: 'crop_tomato',
        name: 'Tomato',
        sinhalaName: 'තක්කාලි',
        category: 'Fruit Vegetable',
        maturityDays: 80,
        expectedYieldKgPerAcre: 10000,
        currentMarketPricePerKg: 190.0,
        historicalAveragePricePerKg: 175.0,
        iconEmoji: '🍅',
      ),
      const Crop(
        id: 'crop_bellpepper',
        name: 'Bell Pepper (Capsicum)',
        sinhalaName: 'මාළු මිරිස්',
        category: 'High Value',
        maturityDays: 85,
        expectedYieldKgPerAcre: 5000,
        currentMarketPricePerKg: 480.0,
        historicalAveragePricePerKg: 380.0,
        iconEmoji: '🫑',
      ),
    ];
  }

  static Map<String, CropRiskAnalysis> getRiskAnalyses() {
    return {
      'crop_leeks': const CropRiskAnalysis(
        cropId: 'crop_leeks',
        cropName: 'Leeks',
        cropEmoji: '🥬',
        riskLevel: CropRiskLevel.critical,
        regionalPlantedAcres: 620.0,
        regionalMaxTargetAcres: 380.0,
        saturationPercentage: 163.2,
        currentMarketPriceLkr: 220.0,
        predictedHarvestPriceLkr: 95.0,
        priceDropRiskPercentage: 56.8,
        warningMessage: 'CRITICAL ALERT: Over 620 acres already registered in Bandarawela and Nuwara Eliya. High risk of 57% price crash at harvest time in May/June.',
        agronomicAdvice: 'Agrarian Services recommend pausing new Leek cultivation. Shift to short-cycle root crops to capture upcoming deficit windows.',
        alternativeRecommendations: [
          CropRecommendation(
            cropId: 'crop_beetroot',
            cropName: 'Beetroot',
            emoji: '🟣',
            reason: 'Low regional planting volume (only 42% capacity). High demand projected from Western Province wholesalers.',
            profitBoostPercentage: 38.5,
            estimatedRevenuePerAcreLkr: 1820000,
          ),
          CropRecommendation(
            cropId: 'crop_bellpepper',
            cropName: 'Bell Pepper (Capsicum)',
            emoji: '🫑',
            reason: 'Premium price stability and short 85-day cycle. Strong institutional buyer demand.',
            profitBoostPercentage: 54.0,
            estimatedRevenuePerAcreLkr: 2400000,
          ),
        ],
      ),
      'crop_cabbage': const CropRiskAnalysis(
        cropId: 'crop_cabbage',
        cropName: 'Cabbage',
        cropEmoji: '🥗',
        riskLevel: CropRiskLevel.moderate,
        regionalPlantedAcres: 410.0,
        regionalMaxTargetAcres: 450.0,
        saturationPercentage: 91.1,
        currentMarketPriceLkr: 140.0,
        predictedHarvestPriceLkr: 115.0,
        priceDropRiskPercentage: 17.8,
        warningMessage: 'CAUTION: Cabbage planting has reached 91% of recommended regional volume. Further planting may depress retail price.',
        agronomicAdvice: 'Proceed with staggered planting or secure forward sales agreement before nursery seeding.',
        alternativeRecommendations: [
          CropRecommendation(
            cropId: 'crop_beans',
            cropName: 'Green Beans',
            emoji: '🫘',
            reason: 'High turnover 60-day cycle with steady daily auction bidding in Dambulla & Manning markets.',
            profitBoostPercentage: 28.0,
            estimatedRevenuePerAcreLkr: 1530000,
          ),
        ],
      ),
      'crop_carrot': const CropRiskAnalysis(
        cropId: 'crop_carrot',
        cropName: 'Carrots',
        cropEmoji: '🥕',
        riskLevel: CropRiskLevel.moderate,
        regionalPlantedAcres: 440.0,
        regionalMaxTargetAcres: 500.0,
        saturationPercentage: 88.0,
        currentMarketPriceLkr: 310.0,
        predictedHarvestPriceLkr: 260.0,
        priceDropRiskPercentage: 16.1,
        warningMessage: 'CAUTION: Carrot acreage has reached 88% of regional threshold. Monitor local market closely.',
        agronomicAdvice: 'Stagger planting cycles to avoid peak arrival weeks.',
        alternativeRecommendations: [],
      ),
      'crop_beetroot': const CropRiskAnalysis(
        cropId: 'crop_beetroot',
        cropName: 'Beetroot',
        cropEmoji: '🟣',
        riskLevel: CropRiskLevel.safe,
        regionalPlantedAcres: 160.0,
        regionalMaxTargetAcres: 380.0,
        saturationPercentage: 42.1,
        currentMarketPriceLkr: 280.0,
        predictedHarvestPriceLkr: 295.0,
        priceDropRiskPercentage: 0.0,
        warningMessage: 'HIGHLY RECOMMENDED: Regional deficit identified. Market demand is 2.3x current planted volume.',
        agronomicAdvice: 'Ideal for 70-day rotation. Fits perfectly before monsoon onset.',
        alternativeRecommendations: [],
      ),
      'crop_beans': const CropRiskAnalysis(
        cropId: 'crop_beans',
        cropName: 'Green Beans',
        cropEmoji: '🫘',
        riskLevel: CropRiskLevel.safe,
        regionalPlantedAcres: 180.0,
        regionalMaxTargetAcres: 350.0,
        saturationPercentage: 51.4,
        currentMarketPriceLkr: 340.0,
        predictedHarvestPriceLkr: 355.0,
        priceDropRiskPercentage: 0.0,
        warningMessage: 'SAFE: Steady demand with balanced regional planting.',
        agronomicAdvice: 'Ensure adequate trellis support to maximize yield.',
        alternativeRecommendations: [],
      ),
      'crop_tomato': const CropRiskAnalysis(
        cropId: 'crop_tomato',
        cropName: 'Tomato',
        cropEmoji: '🍅',
        riskLevel: CropRiskLevel.moderate,
        regionalPlantedAcres: 290.0,
        regionalMaxTargetAcres: 320.0,
        saturationPercentage: 90.6,
        currentMarketPriceLkr: 190.0,
        predictedHarvestPriceLkr: 160.0,
        priceDropRiskPercentage: 15.7,
        warningMessage: 'MODERATE RISK: Substantial tomato harvest scheduled in Welimada region during the same timeframe.',
        agronomicAdvice: 'Consider greenhouse or staggered planting to avoid peak arrival weeks.',
        alternativeRecommendations: [
          CropRecommendation(
            cropId: 'crop_bellpepper',
            cropName: 'Bell Pepper',
            emoji: '🫑',
            reason: 'Much higher price resilience against rain damage compared to open-field tomatoes.',
            profitBoostPercentage: 42.0,
            estimatedRevenuePerAcreLkr: 2400000,
          ),
        ],
      ),
      'crop_bellpepper': const CropRiskAnalysis(
        cropId: 'crop_bellpepper',
        cropName: 'Bell Pepper (Capsicum)',
        cropEmoji: '🫑',
        riskLevel: CropRiskLevel.safe,
        regionalPlantedAcres: 95.0,
        regionalMaxTargetAcres: 260.0,
        saturationPercentage: 36.5,
        currentMarketPriceLkr: 480.0,
        predictedHarvestPriceLkr: 510.0,
        priceDropRiskPercentage: 0.0,
        warningMessage: 'HIGH PROFIT POTENTIAL: Low supply across all Central Province markets. Premium buyer interest guaranteed.',
        agronomicAdvice: 'Apply organic mulch for moisture retention during flowering stage.',
        alternativeRecommendations: [],
      ),
    };
  }

  static FarmerProfile getInitialFarmerProfile() {
    return FarmerProfile(
      id: 'farmer_nirman_01',
      fullName: 'Nirman',
      phone: '+94 77 123 4567',
      nic: '200123456789',
      agrarianDivision: 'Bandarawela',
      gndDivision: 'Heeloya West (GND 142)',
      totalLandAcres: 3.5,
      activePlantings: [
        PlantedCropEntry(
          id: 'plant_001',
          cropId: 'crop_leeks',
          cropName: 'Leeks',
          cropEmoji: '🥬',
          allocatedAcres: 1.0,
          plantingDate: DateTime.now().subtract(const Duration(days: 55)),
          expectedHarvestDate: DateTime.now().add(const Duration(days: 35)),
          projectedYieldKg: 8000,
          status: 'growing',
          agrarianDivision: 'Bandarawela',
        ),
        PlantedCropEntry(
          id: 'plant_002',
          cropId: 'crop_carrot',
          cropName: 'Carrots',
          cropEmoji: '🥕',
          allocatedAcres: 0.6,
          plantingDate: DateTime.now().subtract(const Duration(days: 42)),
          expectedHarvestDate: DateTime.now().add(const Duration(days: 48)),
          projectedYieldKg: 4500,
          status: 'growing',
          agrarianDivision: 'Bandarawela',
        ),
        PlantedCropEntry(
          id: 'plant_003',
          cropId: 'crop_beetroot',
          cropName: 'Beetroot',
          cropEmoji: '🟣',
          allocatedAcres: 0.5,
          plantingDate: DateTime.now().subtract(const Duration(days: 58)),
          expectedHarvestDate: DateTime.now().add(const Duration(days: 12)),
          projectedYieldKg: 3250,
          status: 'growing',
          agrarianDivision: 'Bandarawela',
        ),
      ],
    );
  }

  static List<SurplusListing> getNearbySurplusListings() {
    return [
      SurplusListing(
        id: 'surplus_01',
        farmerId: 'farmer_sunil',
        farmerName: 'Sunil Bandara',
        farmerPhone: '+94 71 456 7890',
        cropName: 'Leeks',
        cropEmoji: '🥬',
        availableQuantityKg: 450,
        askingPricePerKgLkr: 130.0,
        regularMarketPricePerKgLkr: 220.0,
        harvestedDate: DateTime.now().subtract(const Duration(hours: 6)),
        farmLocation: 'Bandarawela - Kinigama Road',
        distanceKm: 2.3,
        isUrgent: true,
        qualityGrade: 'Grade A Local',
        notes: 'Freshly harvested this morning. Ideal for wedding halls and event caterers. Ready for pickup.',
      ),
      SurplusListing(
        id: 'surplus_02',
        farmerId: 'farmer_kamal',
        farmerName: 'Kamal Jayawardena',
        farmerPhone: '+94 76 987 6543',
        cropName: 'Cabbage',
        cropEmoji: '🥗',
        availableQuantityKg: 800,
        askingPricePerKgLkr: 90.0,
        regularMarketPricePerKgLkr: 140.0,
        harvestedDate: DateTime.now().subtract(const Duration(hours: 12)),
        farmLocation: 'Diyatalawa Road, Bandarawela',
        distanceKm: 3.8,
        isUrgent: false,
        qualityGrade: 'Grade A Export',
        notes: 'Clean tight heads, no pesticide residue, packed in 25kg crates.',
      ),
      SurplusListing(
        id: 'surplus_03',
        farmerId: 'farmer_sarath',
        farmerName: 'Sarath Gunasekara',
        farmerPhone: '+94 77 332 1100',
        cropName: 'Tomatoes',
        cropEmoji: '🍅',
        availableQuantityKg: 300,
        askingPricePerKgLkr: 120.0,
        regularMarketPricePerKgLkr: 190.0,
        harvestedDate: DateTime.now().subtract(const Duration(hours: 4)),
        farmLocation: 'Heeloya Valley',
        distanceKm: 1.5,
        isUrgent: true,
        qualityGrade: 'Grade A Table',
        notes: 'Firm ripe red tomatoes. Must clear within 24 hours to prevent spoilage.',
      ),
      SurplusListing(
        id: 'surplus_04',
        farmerId: 'farmer_priyantha',
        farmerName: 'Priyantha Alwis',
        farmerPhone: '+94 70 554 4321',
        cropName: 'Beetroot',
        cropEmoji: '🟣',
        availableQuantityKg: 500,
        askingPricePerKgLkr: 210.0,
        regularMarketPricePerKgLkr: 280.0,
        harvestedDate: DateTime.now().subtract(const Duration(hours: 18)),
        farmLocation: 'Welimada Junction, Bandarawela',
        distanceKm: 4.6,
        isUrgent: false,
        qualityGrade: 'Grade A',
        notes: 'Washed and graded. Medium size roots, sweet quality.',
      ),
    ];
  }

  static List<AgrarianNotice> getAgrarianNotices() {
    return [
      AgrarianNotice(
        id: 'notice_01',
        title: 'Govt Advisory: Over-supply in Leeks',
        department: 'Department of Agrarian Development, Bandarawela',
        issuedBy: 'Mrs. Athukorala (Divisional Agrarian Officer)',
        description: 'Prices expected to dip. Delay planting new cohorts. Cultivation records indicate over 620 acres of leeks sown in Bandarawela. Agrarian Services recommend pausing new sowing and shifting to beetroot or green beans.',
        date: DateTime.now().subtract(const Duration(days: 1)),
        priority: NoticePriority.urgent,
        category: 'Crop Directive',
      ),
      AgrarianNotice(
        id: 'notice_02',
        title: 'Government Fertilizer Subsidy Voucher Disbursement (Maha Season)',
        department: 'Ministry of Agriculture & Plantation Industries',
        issuedBy: 'Agrarian Services Centre - Bandarawela',
        description: 'Registered smallholder farmers can claim digital subsidy vouchers for organic and NPK fertilizers at the Bandarawela Agrarian Services Centre from Monday onwards with NIC verification.',
        date: DateTime.now().subtract(const Duration(days: 3)),
        priority: NoticePriority.high,
        category: 'Subsidy',
      ),
      AgrarianNotice(
        id: 'notice_03',
        title: 'Localized Heavy Rainfall & Fungal Blight Advisory',
        department: 'Department of Meteorology & Agriculture Extension',
        issuedBy: 'Badulla District Agricultural Office',
        description: 'Upcountry tea and exotic vegetable cultivation zones expect intermittent evening downpours over the next 5 days. Inspect nursery beds for late blight in tomatoes and potato crops.',
        date: DateTime.now().subtract(const Duration(days: 5)),
        priority: NoticePriority.medium,
        category: 'Weather Warning',
      ),
    ];
  }
}
